version: 2
updates:
  # Update Composer dependencies
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        patterns:
          - "patch"
      minor-updates:
        patterns:
          - "minor"
    commit-message: "dependabot"
    auto-merge: true

  # Update Docker nginx dependencies
  - package-ecosystem: "docker"
    directory: "/docker/nginx"
    schedule:
      interval: "weekly"

  # Update Docker php dependencies
  - package-ecosystem: "docker"
    directory: "/docker/php"
    schedule:
      interval: "weekly"